---
title: "Cells"
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(ggridges)
library(here)

source(here("_common.R"))

cells <-
  read_csv(here("data", "cells.csv"), col_types = cols(location = col_factor(levels = locations))) |> 
  mutate(celltype = fct(celltype) |> fct_reorder(conc, .fun = max, .na.rm = T)) |> 
  mutate(season = make_season(date))

filter_eukaryotes <- function(data){
  data |> filter(celltype %in% c("nanoeuka", "picoeuka"))
}

filter_cyanobacteria <- function(data){
  data |> filter(celltype %in% c("prochloro", "synecho"))
}

filter_nucleic_acid <- function(data){
  data |> filter(celltype %in% c("hna", "lna"))
}
```

## Introduction

```{r}
cells |> 
  filter(!is.na(conc) & conc > 0) |> 
  ggplot(aes(x = conc, y = celltype)) +
  geom_density_ridges(aes(fill = celltype), alpha = .5, scale = 3, bandwidth = .09, show.legend = F) +
  scale_y_discrete(labels = labels_celltype, name = NULL) +
  scale_x_log10(labels = scales::label_number()) +
  coord_cartesian(clip = "off") +
  labs(x = "Concentration (cells/mL)") +
  theme_classic()
```

## Eukaryotic plankton distribution

```{r}
cells |>
  filter_eukaryotes() |> 
  filter(!is.na(conc)) |> 
  ggplot(aes(y = fct_rev(location), x = conc)) +
  geom_boxplot(outliers = F) +
  facet_wrap(~ celltype, scales = "free_x", labeller = as_labeller(labels_celltype)) +
  geom_jitter(alpha = .3, width = .3) +
  scale_y_discrete(labels = labels_location) +
  scale_x_log10() +
  labs(x = "concentration (μM)", y = "") +
  theme_bw()
```

```{r}
cells |> 
  filter_eukaryotes() |> 
  filter(!is.na(conc)) |> 
  filter_analysis() |> 
  ggplot(aes(x = date, conc, shape = location, color = location)) +
  geom_point() +
  facet_wrap(
    ~ celltype, nrow = 2, scale = "free_y", labeller = as_labeller(labels_celltype)
  ) +
  scale_shape_discrete(labels = labels_location) +
  scale_color_discrete(labels = labels_location) +
  scale_y_log10() +
  labs(y = "concentration (μM)", shape = "", color = "") +
  theme_bw() +
  theme(axis.title.x = element_blank(), legend.position = "bottom")
```

```{r}
cells |> 
  filter_eukaryotes() |> 
  filter(!is.na(conc)) |> 
  filter(!is.na(season)) |> 
  ggplot(aes(x = season, conc)) +
  geom_boxplot(outliers = F) +
  facet_wrap(
    ~ celltype, nrow = 2, scale = "free_y", labeller = as_labeller(labels_celltype)
  ) +
  geom_jitter(alpha = .3, width = .3) +
  scale_x_discrete(labels = labels_season) +
  scale_y_log10() +
  labs(y = "concentration (μM)") +
  theme_bw() +
  theme(axis.title.x = element_blank())
```
```{r}
cells |> 
  filter_eukaryotes() |> 
  filter(!is.na(conc)) |> 
  filter_analysis() |> 
  ggplot(aes(x = season, conc)) +
  geom_boxplot(outliers = F) +
  facet_grid(
    location ~ celltype, scale = "free",
    labeller = as_labeller(c(labels_location, labels_celltype))
  ) +
  geom_jitter(alpha = .3, width = .3) +
  scale_x_discrete(labels = labels_season) +
  scale_y_log10() +
  labs(x = "", y = "concentration (μM)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 20, vjust = .5))
```

## Cyanobacteria distribution

```{r}
cells |>
  filter_cyanobacteria() |> 
  filter(!is.na(conc)) |> 
  ggplot(aes(y = location, x = conc)) +
  geom_boxplot(outliers = F) +
  facet_wrap(~ celltype, scales = "free_x", labeller = as_labeller(labels_celltype)) +
  geom_jitter(alpha = .3, width = .3) +
  scale_y_discrete(labels = labels_location) +
  scale_x_log10() +
  labs(x = "concentration (μM)", y = "") +
  theme_bw()
```

```{r}
cells |> 
  filter_cyanobacteria() |> 
  filter(!is.na(conc)) |> 
  filter_analysis() |> 
  ggplot(aes(x = date, conc, shape = location, color = location)) +
  geom_point() +
  facet_wrap(
    ~ celltype, nrow = 2, scale = "free_y", labeller = as_labeller(labels_celltype)
  ) +
  scale_shape_discrete(labels = labels_location) +
  scale_color_discrete(labels = labels_location) +
  scale_y_log10() +
  labs(y = "concentration (μM)", shape = "", color = "") +
  theme_bw() +
  theme(axis.title.x = element_blank(), legend.position = "bottom")
```

```{r}
cells |> 
  filter_cyanobacteria() |> 
  filter(!is.na(conc)) |> 
  filter(!is.na(season)) |> 
  ggplot(aes(x = season, conc)) +
  geom_boxplot(outliers = F) +
  facet_wrap(
    ~ celltype, nrow = 2, scale = "free_y", labeller = as_labeller(labels_celltype)
  ) +
  geom_jitter(alpha = .3, width = .3) +
  scale_x_discrete(labels = labels_season) +
  scale_y_log10() +
  labs(y = "concentration (μM)") +
  theme_bw() +
  theme(axis.title.x = element_blank())
```

```{r}
cells |> 
  filter_cyanobacteria() |> 
  filter(!is.na(conc)) |> 
  filter_analysis() |> 
  ggplot(aes(x = season, conc)) +
  geom_boxplot(outliers = F) +
  facet_grid(
    location ~ celltype, scale = "free",
    labeller = as_labeller(c(labels_location, labels_celltype))
  ) +
  geom_jitter(alpha = .3, width = .3) +
  scale_x_discrete(labels = labels_season) +
  scale_y_log10() +
  labs(x = "", y = "concentration (μM)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 20, vjust = .5))
```

## High and Low nucleic acid plankton distribution

```{r}
cells |>
  filter_nucleic_acid() |> 
  filter(!is.na(conc)) |> 
  ggplot(aes(y = location, x = conc)) +
  geom_boxplot(outliers = F) +
  facet_wrap(~ celltype, scales = "free_x", labeller = as_labeller(labels_celltype)) +
  geom_jitter(alpha = .3, width = .3) +
  scale_y_discrete(labels = labels_location) +
  scale_x_log10() +
  labs(x = "concentration (μM)", y = "") +
  theme_bw()
```

```{r}
cells |> 
  filter_nucleic_acid() |> 
  filter(!is.na(conc)) |> 
  filter_analysis() |> 
  ggplot(aes(x = date, conc, shape = location, color = location)) +
  geom_point() +
  facet_wrap(
    ~ celltype, nrow = 2, scale = "free_y", labeller = as_labeller(labels_celltype)
  ) +
  scale_shape_discrete(labels = labels_location) +
  scale_color_discrete(labels = labels_location) +
  scale_y_log10() +
  labs(y = "concentration (μM)", shape = "", color = "") +
  theme_bw() +
  theme(axis.title.x = element_blank(), legend.position = "bottom")
```

```{r}
cells |> 
  filter_nucleic_acid() |> 
  filter(!is.na(conc)) |> 
  filter(!is.na(season)) |> 
  ggplot(aes(x = season, conc)) +
  geom_boxplot(outliers = F) +
  facet_wrap(
    ~ celltype, nrow = 2, scale = "free_y", labeller = as_labeller(labels_celltype)
    ) +
  geom_jitter(alpha = .3, width = .3) +
  scale_x_discrete(labels = labels_season) +
  scale_y_log10() +
  labs(y = "concentration (μM)") +
  theme_bw() +
  theme(axis.title.x = element_blank())
```
```{r}
cells |> 
  filter_nucleic_acid() |> 
  filter(!is.na(conc)) |> 
  filter_analysis() |> 
  ggplot(aes(x = season, conc)) +
  geom_boxplot(outliers = F) +
  facet_grid(
    location ~ celltype, scale = "free",
    labeller = as_labeller(c(labels_location, labels_celltype))
  ) +
  geom_jitter(alpha = .3, width = .3) +
  scale_x_discrete(labels = labels_season) +
  scale_y_log10() +
  labs(x = "", y = "concentration (μM)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 20, vjust = .5))
```