---
title: "Enterococci"
---

```{r}
#| label: setup
#| message: false

library(tidyverse)
library(here)

Sys.setlocale("LC_TIME", "en_US.utf8")

source(here("_common.R"))

samples <-
  read_csv(
    here("data", "samples.csv"),
    col_types = cols(location = col_factor(levels = locations))
  ) |> 
  mutate(date = make_datetime(year, month, day)) |> 
  make_seasons()

enterococci <- 
  read_csv(here("data", "enterococci.csv")) |> 
  make_seasons()
```

## Temporal distribution

```{r}
enterococci |> 
  filter(!is.na(season)) |> 
  ggplot(aes(x = date, y = conc)) +
  geom_point() +
  labs(x = "", y = "Enterococci (CFU/100mL)", caption = "Source: AT Hidrotecnia S.L.") +
  theme_classic()
```

```{r}
enterococci |> 
  filter(!is.na(season)) |> 
  ggplot(aes(x = season, y = conc)) +
  geom_boxplot(outliers = F) +
  geom_jitter(alpha = .3, width = .3) +
  scale_x_discrete(labels = labels_season) +
  labs(x = "", y = "Enterococci (CFU/100mL)", caption = "Source: AT Hidrotecnia S.L.") +
  theme_classic()
```

```{r}
ggplot() +
  geom_point(
    data = samples |> filter_analysis(),
    aes(x = date, y = fct_rev(location), shape = "Samples"),
  ) +
  geom_point(
    data = enterococci |> filter(!is.na(season)) |> mutate(location = "Confital_1"),
    aes(x = date, y = fct_rev(location), size = conc),
    shape = 1
  ) +
  scale_y_discrete(labels = labels_location) +
  scale_size_continuous(range = c(1, 15)) +
  labs(
    x = "", y = "", size = "Enterococci\n(CFU/100mL)",
    shape = "", caption = "Source: AT Hidrotecnia S.L."
    ) +
  scale_x_datetime(breaks = seasons_limits, date_labels = "%b %Y") +
  geom_vline(xintercept = seasons_limits, linetype = "dotted") +
  theme_classic()
```