---
title: "Sea Surface Temperature"
---

```{r}
#| label: setup
#| message: false

Sys.setlocale("LC_TIME", "en_US.utf8")

library(tidyverse)
library(here)

source(here("_common.R"))

temperatures <- 
  read_csv(
    here("data", "temperatures.csv"),
    col_types = cols(location = col_factor(levels = locations))
  ) |> 
  make_seasons()
```

## Temperature distribution

```{r}
temperatures |> 
  ggplot(aes(y = fct_rev(location), x = sst)) +
  geom_boxplot(na.rm = T, outliers = F) +
  geom_jitter(na.rm = T, alpha = .3, width = .3) +
  scale_y_discrete(labels = labels_location) +
  labs(x = "Temperature (ºC)", y = "") +
  theme_bw()
```

```{r}
temperatures |> 
  filter_analysis() |>  
  ggplot(aes(x = date, y = sst)) +
  geom_jitter(na.rm = T) +
  geom_vline(xintercept = seasons_limits, linetype = "dotted") +
  scale_x_datetime(breaks = seasons_limits, date_labels = "%b %Y") +
  labs(x = "", y = "Temperature (ºC)") +
  theme_bw()
```
```{r}
temperatures |> 
  filter_analysis() |> 
  ggplot(aes(x = season, y = sst)) +
  geom_boxplot(na.rm = T, outliers = F) +
  geom_jitter(na.rm = T, alpha = .3, width = .3) +
  scale_x_discrete(labels = labels_season) +
  scale_y_log10() +
  labs(x = "", y = "Temperature (ºC)") +
  theme_bw()
```

